#pragma once

// https://github.com/SpecialKO/SpecialK/blob/main/include/SpecialK/DLL_VERSION.H

#define APP_VERSION_MAJOR    0
#define APP_VERSION_MINOR    0
#define APP_VERSION_BUILD    3
#define APP_VERSION_REVISION 0

#ifndef _A2
  #define _A2(a) #a
  #define _A(a)  _A2(a)
#endif

#define APP_FILE_VERSION_A    _A(APP_VERSION_MAJOR) "." _A(APP_VERSION_MINOR) "." _A(APP_VERSION_BUILD) "." _A(APP_VERSION_REVISION)
#define APP_PRODUCT_VERSION_A _A(APP_VERSION_MAJOR) "." _A(APP_VERSION_MINOR) "." _A(APP_VERSION_BUILD)

#define APP_FILE_VERSION    APP_VERSION_MAJOR,APP_VERSION_MINOR,APP_VERSION_BUILD,APP_VERSION_REVISION
#define APP_PRODUCT_VERSION APP_VERSION_MAJOR,APP_VERSION_MINOR,APP_VERSION_BUILD,APP_VERSION_REVISION
