#pragma once

//
// VERSION_INFO
//
#define APP_VERSION_MAJOR    0
#define APP_VERSION_MINOR    1
#define APP_VERSION_BUILD    0
#define APP_VERSION_REVISION 0

#define APP_STR_HELPER(x) #x
#define APP_STR(x) APP_STR_HELPER(x)

#define APP_VERSION_STR \
    APP_STR(APP_VERSION_MAJOR) "." \
    APP_STR(APP_VERSION_MINOR) "." \
    APP_STR(APP_VERSION_BUILD) "." \
    APP_STR(APP_VERSION_REVISION)

#define APP_VERSION \
    APP_VERSION_MAJOR,APP_VERSION_MINOR,APP_VERSION_BUILD,APP_VERSION_REVISION

//
// ICONS
//
#define IDI_ICON             101
